### ISSUE TITLE
asyncDnsLoookup spelling

### ISSUE THREAD

**Issue by Crazometer** [andris9/fetch#28]
I just spent the last half hour trying to work out what was going on and didn't realise the triple `o` in `asyncDnsLoookup`. Want a pull with the regular spelling e.g. `asyncDnsLookup` for the next breaking release?

**Comment by andris9** [comment]
It seems that the triple-o has been like this for the past 4 years and so far no-one has noticed it, so it's a great find 😀 

This module is more or less frozen by now, so I wouldn't really want to change anything in it. If you copy-paste the property name from the docs then you should end up with correct value.
